"""
VulnProbe - Report Generator
Generates professional vulnerability assessment reports in multiple formats
"""

import json
import os
from datetime import datetime, timezone


# ─────────────────────────────────────────────────────────────────────────────
# TEXT / CONSOLE REPORT
# ─────────────────────────────────────────────────────────────────────────────

RESET  = "\033[0m"
BOLD   = "\033[1m"
RED    = "\033[91m"
YELLOW = "\033[93m"
ORANGE = "\033[33m"
BLUE   = "\033[94m"
CYAN   = "\033[96m"
GREEN  = "\033[92m"
WHITE  = "\033[97m"
GRAY   = "\033[90m"

SEV_COLOR = {
    "CRITICAL": RED,
    "HIGH":     YELLOW,
    "MEDIUM":   ORANGE,
    "LOW":      BLUE,
    "INFO":     CYAN,
}

def _sev(s):
    return f"{SEV_COLOR.get(s, '')}{BOLD}{s:8}{RESET}"

def print_console_report(summary):
    findings = summary["findings"]
    counts   = summary["severity_counts"]
    score    = summary["risk_score"]
    label    = summary["risk_label"]

    bar_color = RED if score >= 80 else YELLOW if score >= 60 else ORANGE if score >= 40 else BLUE
    score_bar = "█" * (score // 5) + "░" * (20 - score // 5)

    print(f"\n{'═'*70}")
    print(f"{BOLD}{WHITE}  VULNERABILITY ASSESSMENT REPORT{RESET}")
    print(f"{'═'*70}")
    print(f"  Target    : {CYAN}{summary['target']}{RESET}")
    print(f"  Host/IP   : {summary['host']} ({summary['ip']})")
    print(f"  Scan Time : {summary['scan_time'][:19].replace('T', ' ')} UTC")
    print(f"  Duration  : {summary['duration_sec']}s")
    print(f"  Open Ports: {', '.join(map(str, summary['open_ports'])) or 'None detected'}")
    print(f"{'─'*70}")

    # Risk score bar
    print(f"\n  {BOLD}RISK SCORE{RESET}")
    print(f"  {bar_color}{score_bar}{RESET}  {bar_color}{BOLD}{score}/100 – {label}{RESET}")

    # Severity breakdown
    print(f"\n  {BOLD}FINDINGS SUMMARY{RESET}  ({summary['total_findings']} total)")
    print(f"  {_sev('CRITICAL')}  {RED}{counts.get('CRITICAL',0)}{RESET}")
    print(f"  {_sev('HIGH')}      {YELLOW}{counts.get('HIGH',0)}{RESET}")
    print(f"  {_sev('MEDIUM')}    {ORANGE}{counts.get('MEDIUM',0)}{RESET}")
    print(f"  {_sev('LOW')}       {BLUE}{counts.get('LOW',0)}{RESET}")
    print(f"  {_sev('INFO')}      {CYAN}{counts.get('INFO',0)}{RESET}")
    print(f"{'─'*70}")

    # Detailed findings grouped by severity
    priority_order = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
    grouped = {sev: [] for sev in priority_order}
    for f in findings:
        grouped[f["severity"]].append(f)

    print(f"\n  {BOLD}DETAILED FINDINGS{RESET}")
    for sev in priority_order:
        group = grouped[sev]
        if not group:
            continue
        print(f"\n  ── {SEV_COLOR[sev]}{BOLD}{sev}{RESET} ({len(group)} issues) {'─'*40}")
        for i, f in enumerate(group, 1):
            print(f"\n  [{i}] {BOLD}{f['title']}{RESET}")
            print(f"      Category    : {f['category']}")
            print(f"      Description : {f['description']}")
            if f.get("evidence"):
                ev = f["evidence"][:120] + ("..." if len(f["evidence"]) > 120 else "")
                print(f"      Evidence    : {GRAY}{ev}{RESET}")
            if f.get("cve"):
                print(f"      CVE         : {RED}{f['cve']}{RESET}")
            if f.get("recommendation"):
                print(f"      Fix         : {GREEN}{f['recommendation']}{RESET}")

    print(f"\n{'═'*70}")
    print(f"  {BOLD}Report generated by VulnProbe{RESET} | For authorized use only")
    print(f"{'═'*70}\n")


# ─────────────────────────────────────────────────────────────────────────────
# JSON REPORT
# ─────────────────────────────────────────────────────────────────────────────

def save_json_report(summary, output_path):
    with open(output_path, "w") as f:
        json.dump(summary, f, indent=2, default=str)
    print(f"  [+] JSON report saved: {output_path}")


# ─────────────────────────────────────────────────────────────────────────────
# PDF REPORT
# ─────────────────────────────────────────────────────────────────────────────

def save_pdf_report(summary, output_path):
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm, cm
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            HRFlowable, PageBreak
        )
        from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT

        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            leftMargin=20*mm, rightMargin=20*mm,
            topMargin=25*mm, bottomMargin=20*mm
        )

        # ── Color palette
        C_BG        = colors.HexColor("#0D1117")
        C_PANEL     = colors.HexColor("#161B22")
        C_BORDER    = colors.HexColor("#30363D")
        C_CRITICAL  = colors.HexColor("#FF4444")
        C_HIGH      = colors.HexColor("#FF8C00")
        C_MEDIUM    = colors.HexColor("#FFD700")
        C_LOW       = colors.HexColor("#4FC3F7")
        C_INFO      = colors.HexColor("#81C784")
        C_TEXT      = colors.HexColor("#E6EDF3")
        C_SUBTEXT   = colors.HexColor("#8B949E")
        C_ACCENT    = colors.HexColor("#58A6FF")
        C_GREEN     = colors.HexColor("#3FB950")

        SEV_COLORS_PDF = {
            "CRITICAL": C_CRITICAL,
            "HIGH":     C_HIGH,
            "MEDIUM":   C_MEDIUM,
            "LOW":      C_LOW,
            "INFO":     C_INFO,
        }

        # ── Styles
        styles = getSampleStyleSheet()

        def s(name, **kw):
            return ParagraphStyle(name, **kw)

        style_title = s("title",
            fontName="Helvetica-Bold", fontSize=22, textColor=C_TEXT,
            spaceAfter=4, alignment=TA_LEFT)

        style_subtitle = s("subtitle",
            fontName="Helvetica", fontSize=10, textColor=C_SUBTEXT,
            spaceAfter=2, alignment=TA_LEFT)

        style_section = s("section",
            fontName="Helvetica-Bold", fontSize=13, textColor=C_ACCENT,
            spaceBefore=12, spaceAfter=6)

        style_body = s("body",
            fontName="Helvetica", fontSize=9, textColor=C_TEXT,
            spaceAfter=3, leading=14)

        style_small = s("small",
            fontName="Helvetica", fontSize=8, textColor=C_SUBTEXT,
            spaceAfter=2, leading=12)

        style_mono = s("mono",
            fontName="Courier", fontSize=8, textColor=C_SUBTEXT,
            spaceAfter=2, leading=12)

        style_bold = s("bold",
            fontName="Helvetica-Bold", fontSize=9, textColor=C_TEXT,
            spaceAfter=2)

        story = []

        # ── HEADER BLOCK
        header_data = [[
            Paragraph("🔍 VULNERABILITY ASSESSMENT REPORT", style_title),
            Paragraph(
                f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
                s("hdr_date", fontName="Helvetica", fontSize=8,
                  textColor=C_SUBTEXT, alignment=TA_RIGHT)
            )
        ]]
        header_table = Table(header_data, colWidths=["75%", "25%"])
        header_table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,-1), C_BG),
            ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
            ("BOTTOMPADDING", (0,0), (-1,-1), 10),
            ("TOPPADDING", (0,0), (-1,-1), 10),
            ("LEFTPADDING", (0,0), (-1,-1), 8),
            ("RIGHTPADDING", (0,0), (-1,-1), 8),
        ]))
        story.append(header_table)
        story.append(Spacer(1, 4*mm))

        # ── SCAN INFO TABLE
        counts  = summary["severity_counts"]
        score   = summary["risk_score"]
        label   = summary["risk_label"]
        score_c = SEV_COLORS_PDF.get(label, C_INFO)

        info_data = [
            ["Target",    summary["target"],      "Risk Score", f"{score}/100 – {label}"],
            ["Host",      f"{summary['host']} ({summary['ip']})", "Duration", f"{summary['duration_sec']}s"],
            ["Scan Time", summary["scan_time"][:19].replace("T", " ") + " UTC",
             "Open Ports", ", ".join(map(str, summary["open_ports"])) or "None"],
        ]

        def cell(txt, bold=False, color=C_TEXT, align=TA_LEFT):
            st = s(f"c_{id(txt)}", fontName="Helvetica-Bold" if bold else "Helvetica",
                   fontSize=8.5, textColor=color, alignment=align)
            return Paragraph(txt, st)

        fmt_info = [
            [cell(r[0], bold=True, color=C_SUBTEXT),
             cell(str(r[1]), color=C_TEXT),
             cell(r[2], bold=True, color=C_SUBTEXT),
             cell(str(r[3]), color=score_c if r[2] == "Risk Score" else C_TEXT)]
            for r in info_data
        ]

        info_table = Table(fmt_info, colWidths=["18%", "32%", "18%", "32%"])
        info_table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,-1), C_PANEL),
            ("GRID", (0,0), (-1,-1), 0.5, C_BORDER),
            ("PADDING", (0,0), (-1,-1), 6),
            ("ROWBACKGROUNDS", (0,0), (-1,-1), [C_PANEL, colors.HexColor("#1C2128")]),
        ]))
        story.append(info_table)
        story.append(Spacer(1, 6*mm))

        # ── SEVERITY SUMMARY BAR
        story.append(Paragraph("EXECUTIVE SUMMARY", style_section))

        sev_labels = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
        sev_row = [[
            Table([[Paragraph(sev, s(f"sev_{sev}",
                       fontName="Helvetica-Bold", fontSize=9,
                       textColor=SEV_COLORS_PDF[sev], alignment=TA_CENTER)),
                    Paragraph(str(counts.get(sev, 0)),
                       s(f"cnt_{sev}", fontName="Helvetica-Bold", fontSize=18,
                         textColor=SEV_COLORS_PDF[sev], alignment=TA_CENTER))]],
                  colWidths=["100%"],
                  style=TableStyle([
                      ("BACKGROUND", (0,0), (-1,-1), C_PANEL),
                      ("BOX", (0,0), (-1,-1), 1.5, SEV_COLORS_PDF[sev]),
                      ("PADDING", (0,0), (-1,-1), 6),
                      ("ALIGN", (0,0), (-1,-1), "CENTER"),
                  ]))
            for sev in sev_labels
        ]]
        sev_table = Table(sev_row, colWidths=["20%"]*5)
        sev_table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,-1), C_BG),
            ("LEFTPADDING", (0,0), (-1,-1), 3),
            ("RIGHTPADDING", (0,0), (-1,-1), 3),
        ]))
        story.append(sev_table)
        story.append(Spacer(1, 6*mm))

        # ── RISK GAUGE (text-based)
        bar_filled = int(score / 5)
        bar_str    = "▓" * bar_filled + "░" * (20 - bar_filled)
        gauge_para = Paragraph(
            f"<font name='Courier' size='11' color='#{score_c.hexval()[2:]}'>{bar_str}</font>"
            f"  <b>{score}/100</b>  <font color='#{score_c.hexval()[2:]}'><b>{label}</b></font>",
            s("gauge", fontName="Helvetica", fontSize=11, textColor=C_TEXT,
              spaceAfter=8, leading=16)
        )
        story.append(gauge_para)
        story.append(Spacer(1, 4*mm))

        # ── FINDINGS BY SEVERITY
        story.append(Paragraph("DETAILED FINDINGS", style_section))

        priority = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
        grouped  = {sev: [] for sev in priority}
        for f in summary["findings"]:
            grouped[f["severity"]].append(f)

        for sev in priority:
            grp = grouped[sev]
            if not grp:
                continue

            sc = SEV_COLORS_PDF[sev]
            story.append(HRFlowable(width="100%", thickness=1, color=sc, spaceAfter=4))
            story.append(Paragraph(
                f'<font color="#{sc.hexval()[2:]}"><b>{sev}</b></font>  '
                f'<font color="#{C_SUBTEXT.hexval()[2:]}">— {len(grp)} finding{"s" if len(grp)>1 else ""}</font>',
                s(f"sev_hdr_{sev}", fontName="Helvetica-Bold", fontSize=11,
                  textColor=C_TEXT, spaceAfter=6)
            ))

            for i, f in enumerate(grp):
                # Finding card
                cve_str = f"  <font color='#FF4444'><b>[{f['cve']}]</b></font>" if f.get("cve") else ""
                rows = [
                    [Paragraph(f"<b>#{i+1}  {f['title']}</b>{cve_str}",
                       s("ft", fontName="Helvetica-Bold", fontSize=9.5,
                         textColor=C_TEXT)),
                     Paragraph(f"<b>{sev}</b>",
                       s("fs", fontName="Helvetica-Bold", fontSize=9,
                         textColor=sc, alignment=TA_RIGHT))],
                ]
                detail_rows = []
                fields = [
                    ("Category",    f["category"]),
                    ("Description", f["description"]),
                    ("Evidence",    (f.get("evidence","")[:180] + ("..." if len(f.get("evidence",""))>180 else ""))),
                    ("Fix",         f.get("recommendation","")),
                ]
                for label_txt, val in fields:
                    if val:
                        detail_rows.append([
                            Paragraph(f"<b>{label_txt}</b>",
                               s(f"dl_{label_txt}", fontName="Helvetica-Bold", fontSize=8,
                                 textColor=C_SUBTEXT)),
                            Paragraph(val,
                               s(f"dv_{label_txt}",
                                 fontName="Courier" if label_txt == "Evidence" else "Helvetica",
                                 fontSize=8, textColor=C_TEXT, leading=12))
                        ])

                hdr_t = Table(rows, colWidths=["80%", "20%"])
                hdr_t.setStyle(TableStyle([
                    ("BACKGROUND", (0,0), (-1,-1), colors.HexColor("#21262D")),
                    ("TOPPADDING", (0,0), (-1,-1), 7),
                    ("BOTTOMPADDING", (0,0), (-1,-1), 7),
                    ("LEFTPADDING", (0,0), (-1,-1), 10),
                    ("RIGHTPADDING", (0,0), (-1,-1), 10),
                    ("LINEBELOW", (0,0), (-1,-1), 0.5, C_BORDER),
                ]))

                det_t = Table(detail_rows, colWidths=["18%", "82%"])
                det_t.setStyle(TableStyle([
                    ("BACKGROUND", (0,0), (-1,-1), C_PANEL),
                    ("TOPPADDING", (0,0), (-1,-1), 5),
                    ("BOTTOMPADDING", (0,0), (-1,-1), 5),
                    ("LEFTPADDING", (0,0), (-1,-1), 10),
                    ("RIGHTPADDING", (0,0), (-1,-1), 10),
                    ("GRID", (0,0), (-1,-1), 0.3, C_BORDER),
                ]))

                outer = Table([[hdr_t], [det_t]], colWidths=["100%"])
                outer.setStyle(TableStyle([
                    ("BOX", (0,0), (-1,-1), 1.5, sc),
                    ("LEFTPADDING", (0,0), (-1,-1), 0),
                    ("RIGHTPADDING", (0,0), (-1,-1), 0),
                    ("TOPPADDING", (0,0), (-1,-1), 0),
                    ("BOTTOMPADDING", (0,0), (-1,-1), 0),
                ]))
                story.append(outer)
                story.append(Spacer(1, 4*mm))

        # ── FOOTER
        story.append(PageBreak())
        story.append(Paragraph("REMEDIATION PRIORITY MATRIX", style_section))

        matrix_header = [
            [cell("Priority", bold=True, color=C_SUBTEXT),
             cell("Vulnerability ID", bold=True, color=C_SUBTEXT),
             cell("Title", bold=True, color=C_SUBTEXT),
             cell("Severity", bold=True, color=C_SUBTEXT),
             cell("CVE", bold=True, color=C_SUBTEXT)]
        ]
        sorted_findings = sorted(summary["findings"],
                                  key=lambda x: ["CRITICAL","HIGH","MEDIUM","LOW","INFO"].index(x["severity"]))
        matrix_rows = []
        for i, f in enumerate(sorted_findings[:40], 1):
            sc2 = SEV_COLORS_PDF[f["severity"]]
            matrix_rows.append([
                cell(str(i), color=C_SUBTEXT),
                cell(f["vuln_id"][:25], color=C_ACCENT),
                cell(f["title"][:55], color=C_TEXT),
                Paragraph(f"<b>{f['severity']}</b>",
                    s(f"mx_{i}", fontName="Helvetica-Bold", fontSize=8,
                      textColor=sc2, alignment=TA_CENTER)),
                cell(f.get("cve","–") or "–", color=C_CRITICAL if f.get("cve") else C_SUBTEXT),
            ])

        matrix_table = Table(matrix_header + matrix_rows,
                              colWidths=["8%", "22%", "42%", "14%", "14%"])
        matrix_table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#21262D")),
            ("BACKGROUND", (0,1), (-1,-1), C_PANEL),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [C_PANEL, colors.HexColor("#1C2128")]),
            ("GRID", (0,0), (-1,-1), 0.3, C_BORDER),
            ("PADDING", (0,0), (-1,-1), 5),
            ("ALIGN", (0,0), (-1,-1), "LEFT"),
            ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ]))
        story.append(matrix_table)

        story.append(Spacer(1, 10*mm))
        story.append(Paragraph(
            "⚠  This report was generated for authorized security testing only. "
            "Unauthorized use is illegal and unethical.",
            s("disclaimer", fontName="Helvetica-Oblique", fontSize=8,
              textColor=C_SUBTEXT, alignment=TA_CENTER)
        ))
        story.append(Paragraph(
            "Generated by VulnProbe — Vulnerability Scanner | Internship Security Project",
            s("footer", fontName="Helvetica", fontSize=8,
              textColor=colors.HexColor("#444C56"), alignment=TA_CENTER, spaceBefore=4)
        ))

        doc.build(story)
        print(f"  [+] PDF report saved: {output_path}")
        return True

    except Exception as e:
        print(f"  [!] PDF generation error: {e}")
        return False
